### ISSUE TITLE
New generate-key options

### ISSUE THREAD

**Issue by georgebv** [Kicksaw-Consulting/python-configuration-management#7]
I started using the package and was thinking about adding an option to the `generate-key` command which would create create `.env-*` files automatically.

For example, running `pycm generate-key .env-local` would create a `.env-local` file with a single line `ENC_KEY=<generated_key>`.

This would be equivalent to running `echo "ENC_KEY=$(pycm generate-key | grep -E "^.+=$")" > .env-local`

**Comment by brno32** [comment]
sure that would be handy!
